# A push to the development branch performs the various code styling and testing checks.
name: ğŸ‘€ Code Quality

on:
  push:
    branches:
      - "development"
  
jobs:
  code-quality:
    
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      
      - name: ğŸ”­ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version-file: .python-version
      
      - name: ğŸ›  Install Dependencies
        run: |
            pip install -r pip-requirements.txt
            pip install -e .[development]
      
      - name: ğŸ”¬ Analyse Import Order with iSort
        run: |
          isort --resolve-all-configs --check-only $(git ls-files "*.py")
      
      - name: ğŸ”¬ Analyse Code Style with Black
        run: |
          black --config pyproject.toml --check $(git ls-files "*.py")

      - name: ğŸ”¬ Analyse Code Formatting with Flake8
        run: |
          flake8 --toml-config pyproject.toml $(git ls-files "*.py")
      
      - name: ğŸ”¬ Analyse Type Hinting with MyPy
        run: |
          mypy --install-types
          mypy $(git ls-files "*.py")

      - name: ğŸ”¬ Test with PyTest
        run: |
          pytest tests/